# Generated by Django 5.1.15 on 2026-04-30 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=32)),
                ('event_id', models.CharField(db_index=True, max_length=120)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField()),
                ('signature', models.CharField(blank=True, max_length=300)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_webhook_event',
                'unique_together': {('provider', 'event_id')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_tier', models.CharField(max_length=32)),
                ('amount_bdt', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('sslcommerz', 'SSLCommerz'), ('manual', 'Manual')], max_length=32)),
                ('provider_session_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('provider_ref', models.CharField(blank=True, db_index=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='subscriptions.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_invoice',
                'indexes': [models.Index(fields=['user', 'status'], name='billing_inv_user_id_7efd8f_idx'), models.Index(fields=['status', '-created_at'], name='billing_inv_status_8d03af_idx')],
            },
        ),
    ]
