# Generated by Django 5.1.15 on 2026-04-30 11:19

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('title', models.TextField()),
                ('instrument_type', models.CharField(choices=[('Act', 'Act'), ('Amendment Act', 'Amendment Act'), ('Rules', 'Rules'), ('Amendment Rules', 'Amendment Rules'), ('Ordinance', 'Ordinance'), ('Gazette', 'Gazette'), ('SRO', 'SRO'), ('Order', 'Order'), ('Circular', 'Circular')], max_length=48)),
                ('instrument_number', models.CharField(blank=True, max_length=80)),
                ('date_enacted', models.DateField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('is_parent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('superseded', 'Superseded'), ('active_with_amendments', 'Active with amendments')], default='active', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('amends', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='documents.document')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes_set', to='documents.document')),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['doc_code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('source_file', models.CharField(blank=True, max_length=512)),
                ('raw_json', models.JSONField()),
                ('embedding_model', models.CharField(default='text-embedding-004', max_length=64)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('ingested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('ingested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_document_version',
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion'),
        ),
        migrations.CreateModel(
            name='Crossref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(db_index=True, max_length=16)),
                ('ref_type', models.CharField(choices=[('section', 'Section'), ('rule', 'Rule')], default='section', max_length=8)),
                ('node_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), default=list, size=None)),
                ('references', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=list, size=None)),
                ('referenced_by', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), default=list, size=None)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossrefs', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_crossref',
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(choices=[('docx', '.docx upload'), ('pdf', '.pdf upload'), ('json', 'JSON upload'), ('bulk_zip', 'Bulk zip import')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('source_path', models.CharField(max_length=512)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='documents.document')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_ingestion_job',
            },
        ),
        migrations.CreateModel(
            name='KeywordIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=80)),
                ('doc_code', models.CharField(blank=True, max_length=16)),
                ('prior_doc_code', models.CharField(blank=True, max_length=16)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_indexes', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_keyword_index',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=48)),
                ('parent_node_id', models.CharField(blank=True, db_index=True, max_length=48)),
                ('doc_code', models.CharField(db_index=True, max_length=16)),
                ('title', models.TextField(blank=True)),
                ('start_index', models.IntegerField(blank=True, null=True)),
                ('end_index', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=8)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('section_number', models.CharField(blank=True, db_index=True, max_length=16)),
                ('rule_number', models.CharField(blank=True, db_index=True, max_length=16)),
                ('supersession', models.JSONField(blank=True, default=dict)),
                ('raw_node', models.JSONField(blank=True, default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('is_leaf', models.BooleanField(db_index=True, default=False)),
                ('depth', models.IntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='documents.documentversion')),
            ],
            options={
                'db_table': 'documents_node',
            },
        ),
        migrations.CreateModel(
            name='StatutorySynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8)),
                ('term', models.CharField(db_index=True, max_length=200)),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
            ],
            options={
                'db_table': 'documents_statutory_synonym',
                'unique_together': {('language', 'term')},
            },
        ),
        migrations.CreateModel(
            name='CitationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raised_text', models.CharField(max_length=200)),
                ('expected_section', models.CharField(blank=True, max_length=16)),
                ('chat_message_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_citation_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents_citation_audit',
                'indexes': [models.Index(fields=['status', '-created_at'], name='documents_c_status_e9657d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'is_current'], name='documents_d_documen_4d5ff8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='crossref',
            unique_together={('version', 'section_number', 'ref_type')},
        ),
        migrations.AddIndex(
            model_name='node',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='documents_n_search__00535d_gin'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['doc_code', 'section_number'], name='documents_n_doc_cod_eeb91a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('version', 'node_id')},
        ),
    ]
