# Generated by Django 5.1.15 on 2026-04-30 11:19

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=32, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('label_bn', models.CharField(blank=True, max_length=120)),
                ('daily_request_limit', models.IntegerField()),
                ('rate_limit_per_min', models.IntegerField()),
                ('session_response_cap', models.IntegerField(blank=True, null=True)),
                ('allowed_intents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=list, size=None)),
                ('file_upload_allowed', models.BooleanField(default=False)),
                ('cross_domain_allowed', models.BooleanField(default=False)),
                ('advisory_allowed', models.BooleanField(default=False)),
                ('memory_window_days', models.IntegerField(default=0)),
                ('zone2_max_rows', models.IntegerField(default=3)),
                ('price_bdt', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscriptions_tier_config',
            },
        ),
        migrations.CreateModel(
            name='QuotaCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tier', models.CharField(max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('used', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_quota_counter',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'date'), name='uniq_user_date_quota'), models.UniqueConstraint(condition=models.Q(('guest_token', ''), _negated=True), fields=('guest_token', 'date'), name='uniq_guest_date_quota')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('cancelled', 'Cancelled'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('overridden', 'Overridden')], max_length=24)),
                ('from_tier', models.CharField(blank=True, max_length=32)),
                ('to_tier', models.CharField(max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_event',
                'indexes': [models.Index(fields=['user', '-created_at'], name='subscriptio_user_id_bfea2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('overridden', 'Overridden')], default='active', max_length=16)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('payment_ref', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions_user_subscription',
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_d6003a_idx'), models.Index(fields=['status', 'expires_at'], name='subscriptio_status_8d7635_idx')],
            },
        ),
    ]
