# Generated by Django 5.1.15 on 2026-04-30 11:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseCache',
            fields=[
                ('query_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=32)),
                ('language', models.CharField(max_length=8)),
                ('payload', models.JSONField()),
                ('hits', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('corpus_version', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_response_cache',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(default='en', max_length=8)),
                ('tier_at_start', models.CharField(blank=True, max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('archived', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=32)),
                ('mode', models.CharField(blank=True, choices=[('direct', 'Direct question'), ('situation', 'Situation'), ('document_review', 'Document review'), ('clarification', 'Clarification')], max_length=24)),
                ('retrieved_node_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=48), blank=True, default=list, size=None)),
                ('legal_basis', models.JSONField(blank=True, default=list)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('clarification_options', models.JSONField(blank=True, default=list)),
                ('cta', models.JSONField(blank=True, default=dict)),
                ('next_step', models.CharField(blank=True, max_length=400)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('prompt_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cached', models.BooleanField(default=False)),
                ('verdict', models.CharField(blank=True, max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('storage_path', models.CharField(max_length=500)),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments_set', to='chat.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_file_attachment',
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', '-updated_at'], name='chat_conver_user_id_e2a76b_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['guest_token', '-updated_at'], name='chat_conver_guest_t_6613f0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
    ]
